apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nl33-deploy
  name: nl33-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nl33-deploy
  template:
    metadata:
      labels:
        app: nl33-deploy
    spec:
      containers:
      - image: nlhamo33/bhutan:24
        name: pet
